MasterISS-Agent-Website/ViewModels/Setup/AddCustomerAttachmentViewModel.cs
using MasterISS_Agent_Website_Enums.Enums;
using MasterISS_Agent_Website_Localization;
using MasterISS_Agent_Website_Localization.Customer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MasterISS_Agent_Website.ViewModels.Setup
{
    public class AddCustomerAttachmentViewModel
    {
        [Required]
        public long TaskNo { get; set; }
        public string CustomerName { get; set; }

        [Display(ResourceType = typeof(CustomerModel), Name = "AttachmentType")]
        [Required(ErrorMessageResourceType = typeof(Validation), ErrorMessageResourceName = "Required")]
        public AttachmentType AttachmentType { get; set; }
        public string FileData { get; set; }
        public string Extension { get; set; }
    }
}

MasterISS-Agent-Website/ViewModels/Setup/AddTaskStatusUpdateViewModel.cs
using MasterISS_Agent_Website_Localization;
using MasterISS_Agent_Website_Localization.Setup;
using RadiusR.DB.Enums.CustomerSetup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MasterISS_Agent_Website.ViewModels.Setup
{
    public class AddTaskStatusUpdateViewModel
    {
        [Required]
        public long TaskNo { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "Description")]
        public string Description { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "FaultCodes")]
        [Required(ErrorMessageResourceType = typeof(Validation), ErrorMessageResourceName = "Required")]
        public FaultCodes FaultCode { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "ReservationDate")]
        [RegularExpression("^(3[01]|[12][0-9]|0[1-9]).(1[0-2]|0[1-9]).[0-9]{4} (2[0-3]|[01]?[0-9]):([0-5]?[0-9])$", ErrorMessageResourceType = typeof(Validation), ErrorMessageResourceName = "DateFormatErrorReservationDate")]
        public string ReservationDate { get; set; }

    }
}

MasterISS-Agent-Website/ViewModels/Setup/GetTaskDetailsViewModel.cs
using MasterISS_Agent_Website.ViewModels.Customer;
using MasterISS_Agent_Website_Localization.Customer;
using MasterISS_Agent_Website_Localization.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MasterISS_Agent_Website.ViewModels.Setup
{
    public class GetTaskDetailsViewModel
    {
        [Display(ResourceType = typeof(SetupModel), Name = "TaskNo")]
        public long TaskNo { get; set; }
        [Display(ResourceType = typeof(SetupModel), Name = "XDSLNo")]
        public string XDSLNo { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "SetupAddress")]
        public string Address { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "Username")]
        public string Username { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "Password")]
        public string Password { get; set; }

        public string BBK { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "CustomerPhoneNo")]
        public string CustomerPhoneNo { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "CustomerType")]
        public string CustomerType { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "Details")]
        public string Details { get; set; }

        [Display(ResourceType = typeof(CustomerModel), Name = "HasModem")]
        [UIHint("BoolFormat")]
        public bool HasModem { get; set; }

        [Display(ResourceType = typeof(CustomerModel), Name = "ModemName")]
        public string ModemName { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "XDSLType")]
        public string XDSLType { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "PSTN")]
        public string PSTN { get; set; }

        [Display(ResourceType = typeof(CustomerModel), Name = "TaskUpdates")]
        public IEnumerable<TaskUpdatesDetailListViewModel> TaskUpdates { get; set; }


    }
}

MasterISS-Agent-Website/ViewModels/Setup/GetTaskLineInfoViewModel.cs
using MasterISS_Agent_Website_Localization.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MasterISS_Agent_Website.ViewModels.Setup
{
    public class GetTaskLineInfoViewModel
    {
        [Display(ResourceType = typeof(SetupModel), Name = "XDSLNo")]
        public string XDSLNo { get; set; }
        public string CustomerName { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "IsActive")]
        [UIHint("IsBoolFormat")]
        public bool IsActive { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "DowloadNoiseMargin")]
        public string DownloadNoiseMargin { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "UploadNoiseMargin")]
        public string UploadNoiseMargin { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "CurrentDowloadSpeed")]
        public string CurrentDownloadSpeed { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "CurrentUploadSpeed")]
        public string CurrentUploadSpeed { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "DowloadSpeedCapasity")]
        public string DownloadSpeedCapasity { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "UploadSpeedCapasity")]
        public string UploadSpeedCapasity { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "ShelfCardPort")]
        public string ShelfCardPort { get; set; }
    }
}

MasterISS-Agent-Website/ViewModels/Setup/GetTaskListViewModel.cs
using MasterISS_Agent_Website_Localization;
using MasterISS_Agent_Website_Localization.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MasterISS_Agent_Website.ViewModels.Setup
{
    public class GetTaskListViewModel
    {
        [RegularExpression("^(3[01]|[12][0-9]|0[1-9]).(1[0-2]|0[1-9]).[0-9]{4} (2[0-3]|[01]?[0-9]):([0-5]?[0-9])$", ErrorMessageResourceType = typeof(Validation), ErrorMessageResourceName = "DateFormatErrorReservationDate")]
        [Display(ResourceType = typeof(SetupModel), Name = "StartDate")]
        public string StartDate { get; set; }

        [RegularExpression("^(3[01]|[12][0-9]|0[1-9]).(1[0-2]|0[1-9]).[0-9]{4} (2[0-3]|[01]?[0-9]):([0-5]?[0-9])$", ErrorMessageResourceType = typeof(Validation), ErrorMessageResourceName = "DateFormatErrorReservationDate")]
        [Display(ResourceType = typeof(SetupModel), Name = "EndDate")]
        public string EndDate { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "SearchedName")]
        public string SearchedName { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "SearchedTaskNo")]
        public long? SearchedTaskNo { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "TaskType")]
        public int? TaskType { get; set; }

        [Display(ResourceType = typeof(SetupModel), Name = "TaskStatus")]
        public int? TaskStatus { get; set; }

    }
}

MasterISS-Agent-Website/Controllers/SetupController.cs
using MasterISS_Agent_Website.ViewModels.Setup;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MasterISS_Agent_Website_Localization.Setup;
using MasterISS_Agent_Website_WebServices.SetupWebService;
using NLog;
using RadiusR.DB.Enums.CustomerSetup;
using PagedList;
using RadiusR.DB.Enums;
using MasterISS_Agent_Website_Enums.Enums;
using System.IO;
using MasterISS_Agent_Website_Business.Abstract;
using MasterISS_Agent_Website_Business.Concrete;
using MasterISS_Agent_Website_DataAccess.Concrete.EntityFramework;

namespace MasterISS_Agent_Website.Controllers
{
    [Authorize(Roles = "Admin,SetupManager")]
    public class SetupController : BaseController
    {
        private static Logger LoggerError = LogManager.GetLogger("AppLoggerError");

        SetupServiceWrapper _setupWrapper;

        public SetupController()
        {
            _setupWrapper = new SetupServiceWrapper();
        }

        public ActionResult Index(GetTaskListViewModel getTaskListViewModel, int page = 1, int pageSize = 20)
        {
            getTaskListViewModel = getTaskListViewModel ?? new GetTaskListViewModel();

            ViewBag.TaskTypes = ExtensionMethods.EnumSelectList<TaskTypes, RadiusR.Localization.Lists.CustomerSetup.TaskType>(getTaskListViewModel.TaskType ?? null);
            ViewBag.TaskStatus = ExtensionMethods.EnumSelectList<TaskStatuses, RadiusR.Localization.Lists.CustomerSetup.TaskStatuses>(getTaskListViewModel.TaskStatus ?? null);

            ViewBag.Search = getTaskListViewModel;

            if (ModelState.IsValid)
            {
                if (DateParseOperations.DateIsCorrrect(false, getTaskListViewModel.StartDate, getTaskListViewModel.EndDate))
                {
                    var startDate = DateParseOperations.ConvertDateTime(getTaskListViewModel.StartDate);
                    var endDate = DateParseOperations.ConvertDateTime(getTaskListViewModel.EndDate);

                    if (string.IsNullOrEmpty(getTaskListViewModel.StartDate) || string.IsNullOrEmpty(getTaskListViewModel.EndDate))
                    {
                        startDate = DateTime.Now.AddDays(-29);
                        endDate = DateTime.Now;
                    }
                    if (startDate <= endDate)
                    {
                        if (startDate.Value.AddDays(Properties.Settings.Default.SearchLimit) >= endDate)
                        {
                            getTaskListViewModel.StartDate = startDate.Value.ToString("dd.MM.yyyy HH:mm");
                            getTaskListViewModel.EndDate = endDate.Value.ToString("dd.MM.yyyy HH:mm");

                            var taskList = FilteredTaskList(getTaskListViewModel);
                            if (taskList.Data != null)
                            {
                                var list = taskList.Data.Select(tl => new ListTasksViewModel
                                {
                                    TaskIssueDate = Convert.ToDateTime(tl.TaskIssueDate),
                                    CustomerName = tl.ContactName,
                                    ReservationDate = Convert.ToDateTime(tl.ReservationDate),
                                    Province = tl.Province,
                                    City = tl.City,
                                    SubscriberNo = tl.SubscriberNo,
                                    TaskType = ExtensionMethods.EnumDescription<TaskTypes, RadiusR.Localization.Lists.CustomerSetup.TaskType>(tl.TaskType),
                                    TaskStatus = ExtensionMethods.EnumDescription<TaskStatuses, RadiusR.Localization.Lists.CustomerSetup.TaskStatuses>(tl.TaskStatus),
                                    TaskNo = tl.TaskNo
                                });

                                var totalCount = list.Count();

                                var pagedListmodel = new StaticPagedList<ListTasksViewModel>(list.Skip((page - 1) * pageSize).Take(pageSize), page, pageSize, totalCount);

                                return View(pagedListmodel);

                            }
                            else
                            {
                                ViewBag.ErrorMessage = taskList.ErrorMessage;
                                return View();
                            }
                        }

                        ViewBag.Max30Days = SetupView.Max30Days;
                        return View();
                    }

                    ViewBag.StartTimeBiggerThanEndTime = SetupView.StartDateBiggerThanEndDateError;
                    return View();

                }

                ViewBag.DateFormatIsNotCorrect = SetupView.DateFormatIsNotCorrect;
                return View();

            }

            ViewBag.ValidationError = "Error";
            return View();
        }

        public ActionResult GetTaskDetails(long taskNo)
        {
            var credentialsResponse = _setupWrapper.GetCustomerCredentials(taskNo);

            if (credentialsResponse.ResponseMessage.ErrorCode == 0)
            {
                _setupWrapper = new SetupServiceWrapper();

                var response = _setupWrapper.GetTaskDetails(taskNo);

                if (response.ResponseMessage.ErrorCode == 0)
                {
                    var taskDetails = new GetTaskDetailsViewModel
                    {
                        Address = response.SetupTask.Address,
                        BBK = response.SetupTask.BBK,
                        CustomerPhoneNo = response.SetupTask.CustomerPhoneNo,
                        CustomerType = ExtensionMethods.EnumDescription<CustomerType, RadiusR.Localization.Lists.CustomerType>(response.SetupTask.CustomerType),
                        Details = response.SetupTask.Details,
                        HasModem = response.SetupTask.HasModem,
                        ModemName = response.SetupTask.ModemName,
                        PSTN = response.SetupTask.PSTN,
                        TaskNo = response.SetupTask.TaskNo,
                        XDSLNo = response.SetupTask.XDSLNo,
                        XDSLType = ExtensionMethods.EnumDescription<XDSLTypes, RadiusR.Localization.Lists.XDSLType>(response.SetupTask.XDSLType),
                        Password = credentialsResponse.CustomerCredentials.Password,
                        Username = credentialsResponse.CustomerCredentials.Username,
                        TaskUpdates = response.SetupTask.TaskUpdates.Select(tu => new ViewModels.Customer.TaskUpdatesDetailListViewModel
                        {
                            CreationDate = Convert.ToDateTime(tu.CreationDate),
                            Description = tu.Description,
                            FaultCodes = ExtensionMethods.EnumDescription<FaultCodes, RadiusR.Localization.Lists.CustomerSetup.FaultCodes>(tu.FaultCode),
                            ReservationDate = Convert.ToDateTime(tu.ReservationDate),
                        })
                    };

                    return PartialView("_GetTaskDetails", taskDetails);
                }
                else
                {
                    LoggerError.Fatal($"An error occurred while GetTaskDetails  , ErrorCode:{response.ResponseMessage.ErrorCode} ErrorMessage:{response.ResponseMessage.ErrorMessage} by:{AgentClaimInfo.SubUserMail()}");
                    ViewBag.ErrorMessage = response.ResponseMessage.ErrorMessage;
                    return PartialView("_GetTaskDetails");
                }
            }
            else
            {
                LoggerError.Fatal($"An error occurred while GetCustomerCredentials  , ErrorCode:{credentialsResponse.ResponseMessage.ErrorCode} ErrorMessage:{credentialsResponse.ResponseMessage.ErrorMessage} by:{AgentClaimInfo.SubUserMail()}");
                ViewBag.ErrorMessage = credentialsResponse.ResponseMessage.ErrorMessage;
                return PartialView("_GetTaskDetails");
            }

        }

        public ActionResult UpdateTaskStatus(long taskNo)
        {
            ViewBag.FaultCodes = ExtensionMethods.EnumSelectList<FaultCodes, RadiusR.Localization.Lists.CustomerSetup.FaultCodes>(null);
            var addTaskStatusUpdateViewModel = new AddTaskStatusUpdateViewModel
            {
                TaskNo = taskNo
            };

            return PartialView("_UpdateTaskStatus", addTaskStatusUpdateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateTaskStatus(AddTaskStatusUpdateViewModel addTaskStatusUpdateViewModel)
        {
            if (Enum.IsDefined(typeof(FaultCodes), addTaskStatusUpdateViewModel.FaultCode))
            {
                if (ModelState.IsValid)
                {
                    if ((addTaskStatusUpdateViewModel.FaultCode != FaultCodes.RendezvousMade) && !string.IsNullOrEmpty(addTaskStatusUpdateViewModel.ReservationDate))
                    {
                        addTaskStatusUpdateViewModel.ReservationDate = null;
                    }
                    if ((addTaskStatusUpdateViewModel.FaultCode == FaultCodes.RendezvousMade) && string.IsNullOrEmpty(addTaskStatusUpdateViewModel.ReservationDate))
                    {
                        return Json(new { status = "Failed", ErrorMessage = SetupView.CannotBeLeftBlankrReservationDate }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var response = _setupWrapper.AddTaskStatusUpdate(addTaskStatusUpdateViewModel);
                        if (response.ResponseMessage.ErrorCode == 0)
                        {
                            return Json(new { status = "Success", message = MasterISS_Agent_Website_Localization.View.Successful }, JsonRequestBehavior.AllowGet);
                        }

MasterISS-Agent-Website/Views/Setup/Index.cshtml
@using MasterISS_Agent_Website.ViewModels.Setup
@using PagedList
@using PagedList.Mvc
@using MasterISS_Agent_Website_Localization
@model StaticPagedList<ListTasksViewModel>
@{
    ViewBag.Title = "Kurulum İş Emirleri";

    var search = ViewBag.Search as GetTaskListViewModel ?? new GetTaskListViewModel();
}

@using (Html.BeginForm("Index", "Setup", FormMethod.Get, new { @class = "pt-5 search-form" }))
{
    <div class="row ml-1">
        <div class="col-md-6 col-xl-2 col-sm-12">
            @Html.LabelFor(m => search.StartDate)
            @Html.TextBox("StartDate", search.StartDate, new { @class = "form-control" })
        </div>

        <div class="col-md-6 col-xl-2 col-sm-12">
            @Html.LabelFor(m => search.EndDate)
            @Html.TextBox("EndDate", search.EndDate, new { @class = "form-control" })
        </div>

        <div class="col-md-6 col-xl-2 col-sm-12">
            @Html.LabelFor(m => search.TaskStatus)
            @Html.DropDownList("TaskStatus", (SelectList)ViewBag.TaskStatus, View.Select, new { @class = "form-control datatable-input", @data_col_index = "2" })
        </div>

        <div class="col-md-6 col-xl-2 col-sm-12">
            @Html.LabelFor(m => search.TaskType)
            @Html.DropDownList("TaskType", (SelectList)ViewBag.TaskTypes, View.Select, new { @class = "form-control datatable-input", @data_col_index = "2" })
        </div>

        <div class="col-md-6 col-xl-2 col-sm-12">
            <input type="submit" value="Filtrele" class="btn btn-primary mt-4" />
            @Html.ActionLink("Filtreyi Sıfırla", "Index", "Setup", new { @class = "btn btn-secondary mt-4" })
        </div>
    </div>
}


@if (ViewBag.ValidationError == null && ViewBag.Max30Days == null && ViewBag.StartTimeBiggerThanEndTime == null && ViewBag.ErrorMessage == null && ViewBag.DateFormatIsNotCorrect == null)
{
    if (Model != null && Model.TotalItemCount > 0)
    {
        <section data-info="table section" class="content mt-3">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().TaskIssueDate)</th>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().CustomerName)</th>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().SubscriberNo)</th>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().ReservationDate)</th>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().Province) > @Html.DisplayNameFor(m => m.FirstOrDefault().City)</th>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().TaskStatus)</th>
                                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().TaskType)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.TaskIssueDate)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CustomerName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.SubscriberNo)</td>
                                    <td>@Html.DisplayFor(modelItem => item.ReservationDate)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Province) > @Html.DisplayFor(modelItem => item.City)</td>
                                    <td>@Html.DisplayFor(modelItem => item.TaskStatus)</td>
                                    <td>@Html.DisplayFor(modelItem => item.TaskType)</td>
                                    <td>
                                        <div class="dropdown">
                                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                                Kurulum İşlemleri
                                            </a>
                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                <li>
                                                    <input data-bs-target="#modalCenterGeneric" data-bs-toggle="modal" value="Görev Detayları" dataValue="@item.TaskNo" class="btn btn-info dropdown-item get-task-details" />
                                                </li>
                                                <li>
                                                    <input type="button" data-bs-target="#modalCenterGeneric" data-bs-toggle="modal" class="btn btn-success dropdown-item update-task-status" dataValue="@item.TaskNo" value="Görev Durumunu Güncelle" />
                                                </li>

                                                <li>
                                                    <input type="button" data-bs-target="#modalCenterGeneric" data-bs-toggle="modal" class="btn btn-success dropdown-item customer-session-info" dataValue="@item.TaskNo" value="Oturum Bilgileri" />
                                                </li>

                                                <li>
                                                    <input type="button" data-bs-target="#modalCenterGeneric" data-bs-toggle="modal" class="btn btn-success  dropdown-item customer-line-info" dataValue="@item.TaskNo" value="Hat Bilgileri" />
                                                </li>

                                                <li>
                                                    <input type="button" data-bs-target="#modalCenterGeneric" data-bs-toggle="modal" class="btn btn-success dropdown-item add-customer-file" dataValue="@item.TaskNo" value="Müşteriye Belge Ekle" />
                                                </li>

                                                <li>
                                                    @Html.ActionLink("Sözleşme Bilgileri", "GetCustomerContract", "Setup", new { taskNo = item.TaskNo }, new { @class = "btn btn-info dropdown-item", @target = "_blank" })
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

        <div class="card card-custom">
            <div class="card-body py-7">
                <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <div class="d-flex flex-wrap mr-3">
                        @Html.PagedListPager(Model, page => Url.Action("Index", "Setup", new
                   {
                       page = page,
                   }),
                   new PagedListRenderOptions
                   {
                   })
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="text-muted"> @View.Total @Model.TotalItemCount @View.RecordFound @View.OnThisPage @Model.FirstItemOnPage @View.To @Model.LastItemOnPage @View.Showing</span>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <span class="text-danger">@MasterISS_Agent_Website_Localization.View.NoRecordsFound</span>
    }
}
else
{
    <div class="text-danger">
        <span>@ViewBag.Max30Days</span>
        <span>@ViewBag.ErrorMessage</span>
        <span>@ViewBag.StartTimeBiggerThanEndTime</span>
        <span>@ViewBag.DateFormatIsNotCorrect</span>
    </div>
}

<div class="modal fade" id="modalCenterGeneric" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div id="generic-container">
            </div>
        </div>
    </div>
</div>

@section Javascript{
    <script>

        $(".get-task-details").click(function () {
            var dataValue = $(this).attr("dataValue");
            var postData = { taskNo: dataValue }
            var url = '@Url.Action("GetTaskDetails", "Setup")';
            var container = $("#generic-container");
            container.empty();
            AjaxRequestTypeGetAndReturnHTML(postData, url, container);
          });

        $(".update-task-status").click(function () {
            var dataValue = $(this).attr("dataValue");
            var postData = { taskNo: dataValue }
            var url = '@Url.Action("UpdateTaskStatus", "Setup")';
            var container = $("#generic-container");
            container.empty();
            AjaxRequestTypeGetAndReturnHTML(postData, url, container);
        });

        $(".customer-session-info").click(function () {
            var dataValue = $(this).attr("dataValue");
            var postData = { taskNo: dataValue }
            var url = '@Url.Action("CustomerSessionInfo", "Setup")';
            var container = $("#generic-container");
            container.empty();
            AjaxRequestTypeGetAndReturnHTML(postData, url, container);
        });

        $(".customer-line-info").click(function () {
            var dataValue = $(this).attr("dataValue");
            var postData = { taskNo: dataValue }
            var url = '@Url.Action("CustomerLineInfo", "Setup")';
            var container = $("#generic-container");
            container.empty();
            AjaxRequestTypeGetAndReturnHTML(postData, url, container);
        });

        $(".add-customer-file").click(function () {
            var dataValue = $(this).attr("dataValue");
            var postData = { taskNo: dataValue }
            var url = '@Url.Action("AddCustomerAttachment", "Setup")';
            var container = $("#generic-container");
            container.empty();
            AjaxRequestTypeGetAndReturnHTML(postData, url, container);
        });

        $("#generic-container").on('change', '#FaultCode', function () {
            var value = $(this).val();
            if (value=='9') {
                $(".reservation-date-container").show();
            }
            else {
                $(".reservation-date-container").hide();
            }
        });

        function GenericResult(data, status) {
          if (status = "success") {
              var responseStatus = data.responseJSON.status;
              if (responseStatus == "Success") {
                  var message = data.responseJSON.message;
                  var url='@Url.Action("Index", "Setup")';
                  GetAlert(message, "true",url);
              }
              else if (responseStatus =="FailedAndRedirect") {
                  var redirectMessage = data.responseJSON.ErrorMessage;
                  var urlHome='@Url.Action("Index", "Home")';
                  GetAlert(redirectMessage, "false", urlHome);
              }
              else {
                  $(".error-codes-container").show();
                  $(".error-codes").html(data.responseJSON.ErrorMessage);
              }
          }
          else {
              console.log("Error");
          }
      }
    </script>
}

MasterISS-Agent-Website/Views/Setup/_AddCustomerAttachment.cshtml
@using MasterISS_Agent_Website.ViewModels.Setup
@model AddCustomerAttachmentViewModel

<div class="modal-header">
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("AddCustomerAttachment", "Setup", new AjaxOptions { HttpMethod = "POST", OnComplete = "GenericResult" }, new { @enctype = "multipart/form-data" }))
    {
        <div class="error-codes-container" style="display:none">
            <div class="mt-2 my-4"></div>
            <div class="text-danger error-codes" align="center"></div>
            <div class="mt-2 my-4"></div>
        </div>

        @Html.AntiForgeryToken()
        <div class="mb-3">
            @Html.LabelFor(m => m.AttachmentType, new { @class = "col-form-label" })
            @Html.DropDownListFor(m => m.AttachmentType, (SelectList)ViewBag.AttachmentTypes, MasterISS_Agent_Website_Localization.View.Select, new { @class = "form-control" })
        </div>

        <input type="file" name="uploadingFiles" multiple />

        @Html.HiddenFor(m => m.TaskNo)

        <input type="submit" value="@MasterISS_Agent_Website_Localization.View.Submit" class="btn btn-primary" />
    }
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-light-primary font-weight-bold" data-bs-dismiss="modal">@MasterISS_Agent_Website_Localization.View.Close</button>
</div>