MasterISS-Agent-Website/Controllers/ReportController.cs
using MasterISS_Agent_Website.ViewModels.Report;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MasterISS_Agent_Website.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ReportController : BaseController
    {
        private readonly WebServiceWrapper _wrapper;

        public ReportController()
        {
            _wrapper = new WebServiceWrapper();
        }

        // GET: Report
        public ActionResult Index(int page = 1, int pageSize = 20)
        {
            var response = _wrapper.GetAgentAllowances(page, pageSize);

            if (response.ResponseMessage.ErrorCode == 0)
            {
                var list = response.AgentAllowances.Collections.Select(ac => new ListAgentAllowenceViewModel
                {
                    AllowanceAmount = ac.AllowanceAmount,
                    CollectionId = ac.CollectionID,
                    CreationDate = Convert.ToDateTime(ac.CreationDate),
                    PaymentDate = Convert.ToDateTime(ac.PaymentDate),
                    PaymentStatus = ac.PaymentStatus
                });

                var totalPageCount = response.AgentAllowances.TotalPageCount;

                var totalItemCount = response.AgentAllowances.TotalPageCount == 1 ? list.Count() : totalPageCount * pageSize;

                var pagedList = new StaticPagedList<ListAgentAllowenceViewModel>(list, page, pageSize, totalItemCount);

                return View(pagedList);
            }

            ViewBag.ErrorMessage = ExtensionMethods.GetConvertedErrorMessage(response.ResponseMessage.ErrorCode);

            return View();
        }
    }
}

MasterISS-Agent-Website/Controllers/UserController.cs
using MasterISS_Agent_Website.ViewModels.User;
using MasterISS_Agent_Website_Business.Abstract;
using MasterISS_Agent_Website_Business.Concrete;
using MasterISS_Agent_Website_DataAccess.Concrete.EntityFramework;
using MasterISS_Agent_Website_Enums.Enums;
using MasterISS_Partner_Website_Database;
using NLog;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace MasterISS_Agent_Website.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : BaseController
    {
        private readonly IRoleService _roleService;
        private readonly IRolePermissionService _rolePermissionService;
        private readonly IUserService _userService;
        private readonly IPermissionService _permissionService;
        private readonly WebServiceWrapper _wrapper;

        private static Logger Logger = LogManager.GetLogger("AppLogger");
        private static Logger LoggerError = LogManager.GetLogger("AppLoggerError");

        public UserController()
        {
            _roleService = new RoleManager(new EfRoleDal());
            _rolePermissionService = new RolePermissionManager(new EfRolePermissionDal());
            _userService = new UserManager(new EfUserDal());
            _wrapper = new WebServiceWrapper();
            _permissionService = new PermissionManager(new EfPermissionDal());
        }

        public ActionResult Index()
        {
            var agentId = AgentClaimInfo.AgentId();

            var resultRole = _roleService.GetByFilter(r => r.AgentId == agentId);

            if (resultRole.IsSuccess)
            {
                ViewBag.RoleList = ExtensionMethods.NameValuePairSelectList(resultRole.Data.Select(arl => new KeyValuePair<int, string>(arl.Id, arl.RoleName)), null);
            }
            else
            {
                LoggerError.Fatal($"An error occurred while user Index resultRole : {resultRole.Message} by:{AgentClaimInfo.UserEmail()}");
            }

            using (var db = new MasterISSAgentWebSiteEntities())
            {
                var agentUserList = db.User.Where(u => u.AgentId == agentId).Select(u => new ListAgentUsersViewModel
                {
                    IsEnabled = u.IsEnabled,
                    NameSurname = u.NameSurname,
                    PhoneNumber = u.PhoneNumber,
                    RoleName = db.Role.Where(r => r.Id == u.RoleId).FirstOrDefault().RoleName,
                    UserEmail = u.Username,
                    UserId = u.Id
                }).ToList();

                return View(agentUserList);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UpdateRolePermission(AvailablePermissionList availablePermissionList, int? roleId)
        {
            if (roleId.HasValue)
            {
                var resultRPGet = _rolePermissionService.GetByFilter(rp => rp.RoleId == roleId.Value);

                if (resultRPGet.IsSuccess)
                {
                    var resultRPRemoveRange = _rolePermissionService.RemoveRange(resultRPGet.Data);

                    if (resultRPRemoveRange.IsSuccess)
                    {
                        var addedRolePermission = availablePermissionList.SelectedPermissions.Select(selectedP => new RolePermission
                        {
                            PermissionId = selectedP,
                            RoleId = roleId.Value
                        });

                        var resultRPAddRange = _rolePermissionService.AddRange(addedRolePermission);

                        if (resultRPAddRange.IsSuccess)
                        {
                            return Json(new { status = "Success", message = resultRPAddRange.Message }, JsonRequestBehavior.AllowGet);
                        }

                        LoggerError.Fatal($"An error occurred while UpdateRolePermission(POST) resultRPAddRange : {resultRPAddRange.Message} by:{AgentClaimInfo.UserEmail()}");
                        return Json(new { status = "Failed", ErrorMessage = resultRPAddRange.Message }, JsonRequestBehavior.AllowGet);

                    }

                    LoggerError.Fatal($"An error occurred while UpdateRolePermission(POST) resultRPRemoveRange : {resultRPRemoveRange.Message} by:{AgentClaimInfo.UserEmail()}");
                    return Json(new { status = "Failed", ErrorMessage = resultRPRemoveRange.Message }, JsonRequestBehavior.AllowGet);

                }

                LoggerError.Fatal($"An error occurred while UpdateRolePermission(POST) resultRPGet : {resultRPGet.Message} by:{AgentClaimInfo.UserEmail()}");
                return Json(new { status = "Failed", ErrorMessage = resultRPGet.Message }, JsonRequestBehavior.AllowGet);

            }

            LoggerError.Fatal($"An error occurred while UpdateRolePermission(POST) RoleId Not Found by:{AgentClaimInfo.UserEmail()}");
            return Json(new { status = "Failed", ErrorMessage = MasterISS_Agent_Website_Localization.View.GenericErrorMessage }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult RolePermissionList(int roleId)
        {
            var rolePermissionResult = _rolePermissionService.GetByFilter(rp => rp.RoleId == roleId);


            if (rolePermissionResult.IsSuccess)
            {
                var permissonResult = _permissionService.GetAll();

                if (permissonResult.IsSuccess)
                {
                    var permissionList = permissonResult.Data.Select(p => new AvailablePermissionList
                    {
                        PermissionId = p.Id,
                        PermissionName = p.PermissionName,
                        IsSelected = rolePermissionResult.Data.Select(rp => rp.PermissionId).Contains(p.Id) == true ? "checked" : null
                    }).ToArray();


                    foreach (var item in permissionList)
                    {
                        item.PermissionName = ExtensionMethods.EnumDescription<PermissionList, MasterISS_Agent_Website_Localization.Generic.PermissionList>(item.PermissionId);

                    }
                    return Json(new { status = "Success", list = permissionList }, JsonRequestBehavior.AllowGet);

                }
                LoggerError.Fatal($"An error occurred while RolePermissionList permissonResult : {permissonResult.Message} by:{AgentClaimInfo.UserEmail()}");
                return Json(new { status = "Failed", ErrorMessage = permissonResult.Message }, JsonRequestBehavior.AllowGet);

            }

            LoggerError.Fatal($"An error occurred while RolePermissionList rolePermissionResult : {rolePermissionResult.Message} by:{AgentClaimInfo.UserEmail()}");
            return Json(new { status = "Failed", ErrorMessage = rolePermissionResult.Message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateUser(long userId)
        {
            var resultUser = _userService.GetById(userId);

            if (resultUser.IsSuccess)
            {
                var agentId = AgentClaimInfo.AgentId();

                var resultRole = _roleService.GetByFilter(r => r.IsEnabled == true && r.AgentId == agentId);

                if (resultRole.IsSuccess)
                {
                    ViewBag.RoleList = ExtensionMethods.NameValuePairSelectList(resultRole.Data.Select(arl => new KeyValuePair<int, string>(arl.Id, arl.RoleName)), resultUser.Data.RoleId);

                    var viewModel = new AddAndUpdateUserViewModel
                    {
                        PhoneNumber = resultUser.Data.PhoneNumber,
                        RoleId = resultUser.Data.RoleId,
                        UserEmail = resultUser.Data.Username,
                        UserNameSurname = resultUser.Data.NameSurname,
                        UserId = resultUser.Data.Id,
                        IsEnabled = resultUser.Data.IsEnabled
                    };

                    return PartialView("_UpdateUser", viewModel);
                }

                LoggerError.Fatal($"An error occurred while UpdateUser(Get) resultRole : {resultRole.Message} by:{AgentClaimInfo.UserEmail()}");
                ViewBag.ErrorMessage = resultRole.Message;
                return View();
            }

            LoggerError.Fatal($"An error occurred while UpdateUser(Get) resultUser : {resultUser.Message} by:{AgentClaimInfo.UserEmail()}");
            ViewBag.ErrorMessage = resultUser.Message;

            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UpdateUser(AddAndUpdateUserViewModel addAndUpdateUserViewModel)
        {
            ModelState.Remove("Password");

            if (ModelState.IsValid)
            {
                var resultUser = _userService.GetById(addAndUpdateUserViewModel.UserId);

                if (resultUser.IsSuccess)
                {
                    var agentId = AgentClaimInfo.AgentId();

                    var userControlResult = _userService.Get(u => u.AgentId == agentId && u.Id != resultUser.Data.Id && u.Username == addAndUpdateUserViewModel.UserEmail);
                    if (userControlResult.Data == null)
                    {
                        resultUser.Data.IsEnabled = addAndUpdateUserViewModel.IsEnabled;
                        resultUser.Data.NameSurname = addAndUpdateUserViewModel.UserNameSurname;

                        if (!string.IsNullOrEmpty(addAndUpdateUserViewModel.Password))
                        {
                            resultUser.Data.Password = _wrapper.CalculateHash<SHA256>(addAndUpdateUserViewModel.Password);
                        }

                        resultUser.Data.PhoneNumber = addAndUpdateUserViewModel.PhoneNumber;
                        resultUser.Data.RoleId = addAndUpdateUserViewModel.RoleId;

MasterISS-Agent-Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MasterISS Acentalar</title>
    @*@Styles.Render("~/Content/all-page-css")*@
    <link href="~/Content/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
    <link href="~/Content/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/Content/css/daterangepicker.css" rel="stylesheet" />
    <link href="~/Content/css/all.css" rel="stylesheet" />
    @*<link href="~/Content/css/all.min.css" rel="stylesheet" />*@
    <link href="~/Content/css/icheck-bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/jqvmap.min.css" rel="stylesheet" />
    <link href="~/Content/css/OverlayScrollbars.min.css" rel="stylesheet" />
    <link href="~/Content/css/PagedList.css" rel="stylesheet" />
    <link href="~/Content/css/summernote-bs4.min.css" rel="stylesheet" />
    <link href="~/Content/css/sweetalert2.min.css" rel="stylesheet" />
</head>
@{
    string action = ViewContext.RouteData.Values["action"] as string;
    string controller = ViewContext.RouteData.Values["controller"] as string;
}
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar sidebar-dark-primary elevation-4">

            <a href="@Url.Action("Index","Home")" class="brand-link">
                <img src="~/Content/images/logo/logo.svg" alt="Logo" class="brand-image" style="opacity: .8">
                <span class="brand-text font-weight-light">MasterISS Agent</span>
            </a>

            <div class="sidebar">

                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Content/images/icons/add-client.svg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@ViewBag.Username</a>
                    </div>
                </div>

                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("Index","Home")" class="@Html.Raw(controller == "Home" && action == "Index" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-home"></i>
                                    <p>
                                        Anasayfa
                                    </p>
                                </a>
                            </li>
                        }

                        @if (User.IsInRole("Admin") || User.IsInRole("SaleManager"))
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("NewCustomer", "Customer")" class="@Html.Raw(controller == "Customer" && action == "NewCustomer" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-user-plus"></i>
                                    <p>
                                        Yeni Müşteri
                                    </p>
                                </a>
                            </li>
                        }

                        @if (User.IsInRole("Admin") || User.IsInRole("AssignWorkOrder") || User.IsInRole("SaleManager"))
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("GetAgentSubscriptions", "Customer")" class="@Html.Raw(controller == "Customer" && action == "GetAgentSubscriptions" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-user-check"></i>
                                    <p>
                                        Abone Listesi
                                    </p>
                                </a>
                            </li>

                        }

                        @if (User.IsInRole("Admin") || User.IsInRole("PaymentManager"))
                        {

                            <li class="nav-item">
                                <a href="@Url.Action("GetAgentsPaidBills", "Home")" class="@Html.Raw(controller == "Home" && action == "GetAgentsPaidBills" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-file-invoice-dollar"></i>
                                    <p>
                                        Ödenmiş Fatura Listesi
                                    </p>
                                </a>
                            </li>
                        }

                        @if (User.IsInRole("Admin") || User.IsInRole("SetupManager"))
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Setup")" class="@Html.Raw(controller == "Setup" && action == "Index" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-business-time"></i>
                                    <p>
                                        Kurulum
                                    </p>
                                </a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("Index","User")" class="@Html.Raw(controller == "User" && action == "Index" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-user-friends"></i>
                                    <p>
                                        Kullanıcılar
                                    </p>
                                </a>
                            </li>


                            <li class="nav-item">
                                <a href="@Url.Action("Index","Report")" class="@Html.Raw(controller == "Report" && action == "Index" ? "nav-link active" : "nav-link")">
                                    <i class="nav-icon fas fa-file"></i>
                                    <p>
                                        Hakedişler
                                    </p>
                                </a>
                            </li>

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("SignOut","Account")" class="nav-link btn btn-danger">
                                    <i class="nav-icon fas fa-sign-out-alt"></i>
                                    <p>
                                        Çıkış Yap
                                    </p>
                                </a>
                            </li>
                        }

                    </ul>
                </nav>
            </div>


        </aside>

        <div class="content-wrapper">
            @RenderBody()
        </div>

        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href="/">MasterISS Agent</a></strong>
            <div class="float-right d-none d-sm-inline-block">
                <b>V</b> @ViewBag.Version
            </div>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="~/Scripts/AllPages/adminlte.js"></script>
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    <script src="~/Scripts/AllPages/all.js"></script>
    <script src="~/Scripts/AllPages/ajax-operations.js"></script>
    <script src="~/Scripts/AllPages/Chart.min.js"></script>
    <script src="~/Scripts/AllPages/daterangepicker.js"></script>
    @*<script src="~/Scripts/AllPages/dashboard.js"></script>*@
    <script src="~/Scripts/AllPages/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/sweetalert2.min.js"></script>
    <script src="~/Scripts/AllPages/demo.js"></script>
    <script src="~/Scripts/AllPages/error-messages.js"></script>
    <script src="~/Scripts/AllPages/input-uppercase.js"></script>
    <script src="~/Scripts/AllPages/jquery.knob.min.js"></script>
    <script src="~/Scripts/AllPages/jquery.overlayScrollbars.min.js"></script>
    <script src="~/Scripts/AllPages/jquery.vmap.min.js"></script>
    <script src="~/Scripts/AllPages/moment.min.js"></script>
    <script src="~/Scripts/AllPages/sparkline.js"></script>
    <script src="~/Scripts/AllPages/summernote-bs4.min.js"></script>
    <script src="~/Scripts/AllPages/tempusdominus-bootstrap-4.min.js"></script>
    @*<script src="~/Scripts/bootstrap.js"></script>*@
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @*@Scripts.Render("~/Scripts/all-page-js")*@
    @Scripts.Render("~/Scripts/generic-alert")
    @RenderSection("Javascript", required: false)

</body>
</html>